/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  AccountCreateRequest,
  AccountUpdateRequest,
  HTTPValidationError,
  LoginRequest,
  LoginResponse,
  UserPydantic,
} from '../models/index';
import {
  AccountCreateRequestFromJSON,
  AccountCreateRequestToJSON,
  AccountUpdateRequestFromJSON,
  AccountUpdateRequestToJSON,
  HTTPValidationErrorFromJSON,
  HTTPValidationErrorToJSON,
  LoginRequestFromJSON,
  LoginRequestToJSON,
  LoginResponseFromJSON,
  LoginResponseToJSON,
  UserPydanticFromJSON,
  UserPydanticToJSON,
} from '../models/index';

export interface CreateAccountRequest {
  accountCreateRequest: AccountCreateRequest;
}

export interface LoginOperationRequest {
  loginRequest: LoginRequest;
}

export interface UpdateAccountRequest {
  accountUpdateRequest: AccountUpdateRequest;
}

export interface VerifyChangedEmailRequest {
  token: string;
}

export interface VerifyEmailRequest {
  token: string;
}

/**
 *
 */
export class AccountApi extends runtime.BaseAPI {
  /**
   * Create Account
   */
  async createAccountRaw(
    requestParameters: CreateAccountRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['accountCreateRequest'] == null) {
      throw new runtime.RequiredError(
        'accountCreateRequest',
        'Required parameter "accountCreateRequest" was null or undefined when calling createAccount().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/account`,
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: AccountCreateRequestToJSON(requestParameters['accountCreateRequest']),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * Create Account
   */
  async createAccount(
    requestParameters: CreateAccountRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<any> {
    const response = await this.createAccountRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Get Logged In User
   */
  async getLoggedInUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<UserPydantic>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('HTTPBearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/account/me`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserPydanticFromJSON(jsonValue));
  }

  /**
   * Get Logged In User
   */
  async getLoggedInUser(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<UserPydantic> {
    const response = await this.getLoggedInUserRaw(initOverrides);
    return await response.value();
  }

  /**
   * Login
   */
  async loginRaw(
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<LoginResponse>> {
    if (requestParameters['loginRequest'] == null) {
      throw new runtime.RequiredError(
        'loginRequest',
        'Required parameter "loginRequest" was null or undefined when calling login().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/account/login`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LoginRequestToJSON(requestParameters['loginRequest']),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => LoginResponseFromJSON(jsonValue));
  }

  /**
   * Login
   */
  async login(
    requestParameters: LoginOperationRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<LoginResponse> {
    const response = await this.loginRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Update Account
   */
  async updateAccountRaw(
    requestParameters: UpdateAccountRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['accountUpdateRequest'] == null) {
      throw new runtime.RequiredError(
        'accountUpdateRequest',
        'Required parameter "accountUpdateRequest" was null or undefined when calling updateAccount().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token('HTTPBearer', []);

      if (tokenString) {
        headerParameters['Authorization'] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/account/me`,
        method: 'PATCH',
        headers: headerParameters,
        query: queryParameters,
        body: AccountUpdateRequestToJSON(requestParameters['accountUpdateRequest']),
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * Update Account
   */
  async updateAccount(
    requestParameters: UpdateAccountRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<any> {
    const response = await this.updateAccountRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Verify Changed Email
   */
  async verifyChangedEmailRaw(
    requestParameters: VerifyChangedEmailRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['token'] == null) {
      throw new runtime.RequiredError(
        'token',
        'Required parameter "token" was null or undefined when calling verifyChangedEmail().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['token'] != null) {
      queryParameters['token'] = requestParameters['token'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/account/verify/change`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * Verify Changed Email
   */
  async verifyChangedEmail(
    requestParameters: VerifyChangedEmailRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<any> {
    const response = await this.verifyChangedEmailRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   * Verify Email
   */
  async verifyEmailRaw(
    requestParameters: VerifyEmailRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters['token'] == null) {
      throw new runtime.RequiredError(
        'token',
        'Required parameter "token" was null or undefined when calling verifyEmail().'
      );
    }

    const queryParameters: any = {};

    if (requestParameters['token'] != null) {
      queryParameters['token'] = requestParameters['token'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/account/verify`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<any>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   * Verify Email
   */
  async verifyEmail(
    requestParameters: VerifyEmailRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<any> {
    const response = await this.verifyEmailRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
