repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0'  # Use the sha / tag you want to point at
    hooks:
    - id: eslint
      types: [file]
      args: ['.', '--fix', '--config', '.eslintrc.cjs']
      files: \.([jt]sx?|vue|[cm][jt]s)$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.1.0'
    hooks:
      - id: prettier
        args: ['--write', 'src/']
        files: \.([jt]sx?|vue)$
