/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AccountUpdateRequest
 */
export interface AccountUpdateRequest {
  /**
   * Current password of the user
   * @type {string}
   * @memberof AccountUpdateRequest
   */
  currentPassword: string;
  /**
   *
   * @type {string}
   * @memberof AccountUpdateRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof AccountUpdateRequest
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof AccountUpdateRequest
   */
  newPassword?: string;
}

/**
 * Check if a given object implements the AccountUpdateRequest interface.
 */
export function instanceOfAccountUpdateRequest(value: object): boolean {
  if (!('currentPassword' in value)) return false;
  return true;
}

export function AccountUpdateRequestFromJSON(json: any): AccountUpdateRequest {
  return AccountUpdateRequestFromJSONTyped(json, false);
}

export function AccountUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): AccountUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    currentPassword: json['current_password'],
    name: json['name'] == null ? undefined : json['name'],
    email: json['email'] == null ? undefined : json['email'],
    newPassword: json['new_password'] == null ? undefined : json['new_password'],
  };
}

export function AccountUpdateRequestToJSON(value?: AccountUpdateRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    current_password: value['currentPassword'],
    name: value['name'],
    email: value['email'],
    new_password: value['newPassword'],
  };
}
