/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GradingSystem } from './GradingSystem';
import {
  GradingSystemFromJSON,
  GradingSystemFromJSONTyped,
  GradingSystemToJSON,
} from './GradingSystem';

/**
 *
 * @export
 * @interface CoursePydantic
 */
export interface CoursePydantic {
  /**
   *
   * @type {string}
   * @memberof CoursePydantic
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof CoursePydantic
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof CoursePydantic
   */
  updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof CoursePydantic
   */
  creatorId: string;
  /**
   *
   * @type {string}
   * @memberof CoursePydantic
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CoursePydantic
   */
  description?: string;
  /**
   *
   * @type {GradingSystem}
   * @memberof CoursePydantic
   */
  gradingSystem: GradingSystem;
  /**
   *
   * @type {Array<number>}
   * @memberof CoursePydantic
   */
  gradePointScale: Array<number>;
  /**
   *
   * @type {number}
   * @memberof CoursePydantic
   */
  units: number;
}

/**
 * Check if a given object implements the CoursePydantic interface.
 */
export function instanceOfCoursePydantic(value: object): boolean {
  if (!('id' in value)) return false;
  if (!('createdAt' in value)) return false;
  if (!('updatedAt' in value)) return false;
  if (!('creatorId' in value)) return false;
  if (!('name' in value)) return false;
  if (!('gradingSystem' in value)) return false;
  if (!('gradePointScale' in value)) return false;
  if (!('units' in value)) return false;
  return true;
}

export function CoursePydanticFromJSON(json: any): CoursePydantic {
  return CoursePydanticFromJSONTyped(json, false);
}

export function CoursePydanticFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CoursePydantic {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
    creatorId: json['creator_id'],
    name: json['name'],
    description: json['description'] == null ? undefined : json['description'],
    gradingSystem: GradingSystemFromJSON(json['grading_system']),
    gradePointScale: json['grade_point_scale'],
    units: json['units'],
  };
}

export function CoursePydanticToJSON(value?: CoursePydantic | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
    creator_id: value['creatorId'],
    name: value['name'],
    description: value['description'],
    grading_system: GradingSystemToJSON(value['gradingSystem']),
    grade_point_scale: value['gradePointScale'],
    units: value['units'],
  };
}
