/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CourseMultipleReadRequest
 */
export interface CourseMultipleReadRequest {
  /**
   *
   * @type {Array<string>}
   * @memberof CourseMultipleReadRequest
   */
  ids: Array<string>;
}

/**
 * Check if a given object implements the CourseMultipleReadRequest interface.
 */
export function instanceOfCourseMultipleReadRequest(value: object): boolean {
  if (!('ids' in value)) return false;
  return true;
}

export function CourseMultipleReadRequestFromJSON(json: any): CourseMultipleReadRequest {
  return CourseMultipleReadRequestFromJSONTyped(json, false);
}

export function CourseMultipleReadRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): CourseMultipleReadRequest {
  if (json == null) {
    return json;
  }
  return {
    ids: json['ids'],
  };
}

export function CourseMultipleReadRequestToJSON(value?: CourseMultipleReadRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    ids: value['ids'],
  };
}
