/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 */
export const GradingSystem = {
  Percentage: 'percentage',
  FivePoint: 'five_point',
  FivePointNoFour: 'five_point_no_four',
  FourPoint: 'four_point',
  FourPointWithPointFive: 'four_point_with_point_five',
  FourPointNoOnePointFive: 'four_point_no_one_point_five',
  FourPointQuarterIntervals: 'four_point_quarter_intervals',
  FourPointThirdIntervals: 'four_point_third_intervals',
} as const;
export type GradingSystem = (typeof GradingSystem)[keyof typeof GradingSystem];

export function instanceOfGradingSystem(value: any): boolean {
  return Object.values(GradingSystem).includes(value);
}

export function GradingSystemFromJSON(json: any): GradingSystem {
  return GradingSystemFromJSONTyped(json, false);
}

export function GradingSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): GradingSystem {
  return json as GradingSystem;
}

export function GradingSystemToJSON(value?: GradingSystem | null): any {
  return value as any;
}
