/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface SignupRequest
 */
export interface SignupRequest {
  /**
   * Name of the user
   * @type {string}
   * @memberof SignupRequest
   */
  name: string;
  /**
   * Email address of the user
   * @type {string}
   * @memberof SignupRequest
   */
  email: string;
  /**
   * Password of the user
   * @type {string}
   * @memberof SignupRequest
   */
  password: string;
}

/**
 * Check if a given object implements the SignupRequest interface.
 */
export function instanceOfSignupRequest(value: object): boolean {
  if (!('name' in value)) return false;
  if (!('email' in value)) return false;
  if (!('password' in value)) return false;
  return true;
}

export function SignupRequestFromJSON(json: any): SignupRequest {
  return SignupRequestFromJSONTyped(json, false);
}

export function SignupRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'],
    email: json['email'],
    password: json['password'],
  };
}

export function SignupRequestToJSON(value?: SignupRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    name: value['name'],
    email: value['email'],
    password: value['password'],
  };
}
