/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TermGradesPydantic
 */
export interface TermGradesPydantic {
  /**
   *
   * @type {string}
   * @memberof TermGradesPydantic
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof TermGradesPydantic
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof TermGradesPydantic
   */
  updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof TermGradesPydantic
   */
  termId: string;
  /**
   *
   * @type {string}
   * @memberof TermGradesPydantic
   */
  userId: string;
  /**
   *
   * @type {{ [key: string]: number; }}
   * @memberof TermGradesPydantic
   */
  grades: { [key: string]: number };
}

/**
 * Check if a given object implements the TermGradesPydantic interface.
 */
export function instanceOfTermGradesPydantic(value: object): boolean {
  if (!('id' in value)) return false;
  if (!('createdAt' in value)) return false;
  if (!('updatedAt' in value)) return false;
  if (!('termId' in value)) return false;
  if (!('userId' in value)) return false;
  if (!('grades' in value)) return false;
  return true;
}

export function TermGradesPydanticFromJSON(json: any): TermGradesPydantic {
  return TermGradesPydanticFromJSONTyped(json, false);
}

export function TermGradesPydanticFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TermGradesPydantic {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
    termId: json['term_id'],
    userId: json['user_id'],
    grades: json['grades'],
  };
}

export function TermGradesPydanticToJSON(value?: TermGradesPydantic | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
    term_id: value['termId'],
    user_id: value['userId'],
    grades: value['grades'],
  };
}
