/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface TermUpdateRequest
 */
export interface TermUpdateRequest {
  /**
   *
   * @type {string}
   * @memberof TermUpdateRequest
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof TermUpdateRequest
   */
  description?: string;
  /**
   *
   * @type {Array<string>}
   * @memberof TermUpdateRequest
   */
  courses?: Array<string>;
}

/**
 * Check if a given object implements the TermUpdateRequest interface.
 */
export function instanceOfTermUpdateRequest(value: object): boolean {
  return true;
}

export function TermUpdateRequestFromJSON(json: any): TermUpdateRequest {
  return TermUpdateRequestFromJSONTyped(json, false);
}

export function TermUpdateRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): TermUpdateRequest {
  if (json == null) {
    return json;
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    description: json['description'] == null ? undefined : json['description'],
    courses: json['courses'] == null ? undefined : json['courses'],
  };
}

export function TermUpdateRequestToJSON(value?: TermUpdateRequest | null): any {
  if (value == null) {
    return value;
  }
  return {
    name: value['name'],
    description: value['description'],
    courses: value['courses'],
  };
}
