/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserPydantic
 */
export interface UserPydantic {
  /**
   *
   * @type {string}
   * @memberof UserPydantic
   */
  id: string;
  /**
   *
   * @type {Date}
   * @memberof UserPydantic
   */
  createdAt: Date;
  /**
   *
   * @type {Date}
   * @memberof UserPydantic
   */
  updatedAt: Date;
  /**
   *
   * @type {string}
   * @memberof UserPydantic
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UserPydantic
   */
  email: string;
  /**
   *
   * @type {boolean}
   * @memberof UserPydantic
   */
  emailVerified: boolean;
}

/**
 * Check if a given object implements the UserPydantic interface.
 */
export function instanceOfUserPydantic(value: object): boolean {
  if (!('id' in value)) return false;
  if (!('createdAt' in value)) return false;
  if (!('updatedAt' in value)) return false;
  if (!('name' in value)) return false;
  if (!('email' in value)) return false;
  if (!('emailVerified' in value)) return false;
  return true;
}

export function UserPydanticFromJSON(json: any): UserPydantic {
  return UserPydanticFromJSONTyped(json, false);
}

export function UserPydanticFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPydantic {
  if (json == null) {
    return json;
  }
  return {
    id: json['id'],
    createdAt: new Date(json['created_at']),
    updatedAt: new Date(json['updated_at']),
    name: json['name'],
    email: json['email'],
    emailVerified: json['email_verified'],
  };
}

export function UserPydanticToJSON(value?: UserPydantic | null): any {
  if (value == null) {
    return value;
  }
  return {
    id: value['id'],
    created_at: value['createdAt'].toISOString(),
    updated_at: value['updatedAt'].toISOString(),
    name: value['name'],
    email: value['email'],
    email_verified: value['emailVerified'],
  };
}
